ccm/config/routes.rb
Ccm::Application.routes.draw do

  devise_for :users

  resources :configvalues

  resources :enclavequarters

  resources :enclaves

  resources :enclavecontrols

  resources :cybercontrols

  resources :people

  get "home/index"

   root :to => "dashboard#show"

  match 'dashboard/show(/:fcode)(/:id)(/:encntrq)' => 'dashboard#show'
  match 'dashboard/tools' => 'dashboard#tools'
  match 'dashboard/populate(/:year)(/:quarter)' => 'dashboard#populate'
  match 'dashboard/processexcelfile(/:filepath)' => 'dashboard#processexcelfile'
  match 'dashboard/generateappendixa' => 'dashboard#generateappendixa'
end

ccm/app/models/person.rb
# this is just an alias for the User class.  had trouble creating a scaffold for User
# since it's being used by devise for authentication, so rather than trying to figure out
# how devise stuff could co-exist with a scaffold, i just made an alias Person and created a
# scaffold for it.
class Person < ActiveRecord::Base
  class << self
    def table_name
      'users'
    end
  end
end

ccm/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end
end

ccm/app/helpers/people_helper.rb
module PeopleHelper
end

ccm/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.select(:group_name, ['user', 'operator', 'admin', 'super'], {:prompt => 'Select Group'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

ccm/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Sign in count</th>
    <th>Last sign in at</th>
    <th>Last sign in ip</th>
    <th>Group</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.email %></td>
    <td><%= person.sign_in_count %></td>
    <td><%= person.last_sign_in_at %></td>
    <td><%= person.last_sign_in_ip %></td>
    <td><%= person.group_name %></td>
    <td><%= person.created_at %></td>
    <td><%= person.updated_at %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= button_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

ccm/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

ccm/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Encrypted password:</b>
  <%= @person.encrypted_password %>
</p>

<p>
  <b>Reset password token:</b>
  <%= @person.reset_password_token %>
</p>

<p>
  <b>Reset password sent at:</b>
  <%= @person.reset_password_sent_at %>
</p>

<p>
  <b>Remember created at:</b>
  <%= @person.remember_created_at %>
</p>

<p>
  <b>Sign in count:</b>
  <%= @person.sign_in_count %>
</p>

<p>
  <b>Current sign in at:</b>
  <%= @person.current_sign_in_at %>
</p>

<p>
  <b>Last sign in at:</b>
  <%= @person.last_sign_in_at %>
</p>

<p>
  <b>Current sign in ip:</b>
  <%= @person.current_sign_in_ip %>
</p>

<p>
  <b>Last sign in ip:</b>
  <%= @person.last_sign_in_ip %>
</p>

<p>
  <b>Group:</b>
  <%= @person.group_name %>
</p>

<p>
  <b>Created at:</b>
  <%= @person.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @person.updated_at %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>