ccm/config/routes.rb
Ccm::Application.routes.draw do

  devise_for :users

  resources :configvalues

  resources :enclavequarters

  resources :enclaves

  resources :enclavecontrols

  resources :cybercontrols

  resources :people

  get "home/index"

   root :to => "dashboard#show"

  match 'dashboard/show(/:fcode)(/:id)(/:encntrq)' => 'dashboard#show'
  match 'dashboard/tools' => 'dashboard#tools'
  match 'dashboard/populate(/:year)(/:quarter)' => 'dashboard#populate'
  match 'dashboard/processexcelfile(/:filepath)' => 'dashboard#processexcelfile'
  match 'dashboard/generateappendixa' => 'dashboard#generateappendixa'
end

ccm/app/models/enclave.rb
class Enclave < ActiveRecord::Base
  has_many :enclavequarters
  has_many :enclavecontrols

  # internal attribute for finding if the enclave is in use
  def inUse

    # initial value
    result = false
    # make connection to db
    sql = ActiveRecord::Base.connection();
    
    # test if in use
    #count, dummy = sql.execute("SELECT COUNT(*), 0 FROM enclavequarters WHERE enclave_id=#{self.id}").fetch_row
    count = sql.select_value("SELECT COUNT(*) FROM enclavequarters WHERE enclave_id=#{self.id}")
    result = (count.to_i > 0) ? true : false
    
    result

  end

end

ccm/app/controllers/enclaves_controller.rb
class EnclavesController < ApplicationController
  # GET /enclaves
  # GET /enclaves.xml
  def index
    @enclaves = Enclave.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enclaves }
    end
  end

  # GET /enclaves/1
  # GET /enclaves/1.xml
  def show
    @enclave = Enclave.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enclave }
    end
  end

  # GET /enclaves/new
  # GET /enclaves/new.xml
  def new
    @enclave = Enclave.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enclave }
    end
  end

  # GET /enclaves/1/edit
  def edit
    @enclave = Enclave.find(params[:id])
  end

  # POST /enclaves
  # POST /enclaves.xml
  def create
    @enclave = Enclave.new(params[:enclave])

    respond_to do |format|
      if @enclave.save
        format.html { redirect_to(@enclave, :notice => 'Enclave was successfully created.') }
        format.xml  { render :xml => @enclave, :status => :created, :location => @enclave }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enclave.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enclaves/1
  # PUT /enclaves/1.xml
  def update
    @enclave = Enclave.find(params[:id])

    respond_to do |format|
      if @enclave.update_attributes(params[:enclave])
        format.html { redirect_to(@enclave, :notice => 'Enclave was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enclave.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enclaves/1
  # DELETE /enclaves/1.xml
  def destroy
    @enclave = Enclave.find(params[:id])
    @enclave.destroy

    respond_to do |format|
      format.html { redirect_to(enclaves_url) }
      format.xml  { head :ok }
    end
  end
end

ccm/app/helpers/enclaves_helper.rb
module EnclavesHelper
end

ccm/app/views/enclaves/_form.html.erb
<%= form_for(@enclave) do |f| %>
  <% if @enclave.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enclave.errors.count, "error") %> prohibited this enclave from being saved:</h2>

      <ul>
      <% @enclave.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br />
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :long_name %><br />
    <%= f.text_field :long_name %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br />
    <%= f.text_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/enclaves/edit.html.erb
<h1>Editing enclave</h1>

<%= render 'form' %>

<%= link_to 'Show', @enclafe %> |
<%= link_to 'Back', enclaves_path %>

ccm/app/views/enclaves/index.html.erb
<h1>Listing enclaves</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Long name</th>
    <th>Sort order</th>
    <th>Active</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enclaves.each do |enclave| %>
  <tr>
    <td><%= enclave.Name %></td>
    <td><%= enclave.long_name %></td>
    <td><%= enclave.sort_order %></td>
    <td><%= enclave.active %></td>
    <td><%= enclave.created_at %></td>
    <td><%= enclave.updated_at %></td>
    <td><%= link_to 'Show', enclave %></td>
    <td><%= link_to 'Edit', edit_enclave_path(enclave) %></td>
    <td><%= (button_to 'Destroy', enclave, :confirm => 'Are you sure?', :method => :delete ) if (!enclave.inUse) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enclave', new_enclave_path %>

ccm/app/views/enclaves/new.html.erb
<h1>New enclave</h1>

<%= render 'form' %>

<%= link_to 'Back', enclaves_path %>

ccm/app/views/enclaves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @enclave.Name %>
</p>

<p>
  <b>Long name:</b>
  <%= @enclave.long_name %>
</p>

<p>
  <b>Sort order:</b>
  <%= @enclave.sort_order %>
</p>

<p>
  <b>Active:</b>
  <%= @enclave.active %>
</p>

<p>
  <b>Created at:</b>
  <%= @enclave.created_at %>
</p>

<p>
  <b>Updated at:</b>
  <%= @enclave.updated_at %>
</p>


<%= link_to 'Edit', edit_enclave_path(@enclave) %> |
<%= link_to 'Back', enclaves_path %>