ccm/config/routes.rb
Ccm::Application.routes.draw do

  devise_for :users

  resources :configvalues

  resources :enclavequarters

  resources :enclaves

  resources :enclavecontrols

  resources :cybercontrols

  resources :people

  get "home/index"

   root :to => "dashboard#show"

  match 'dashboard/show(/:fcode)(/:id)(/:encntrq)' => 'dashboard#show'
  match 'dashboard/tools' => 'dashboard#tools'
  match 'dashboard/populate(/:year)(/:quarter)' => 'dashboard#populate'
  match 'dashboard/processexcelfile(/:filepath)' => 'dashboard#processexcelfile'
  match 'dashboard/generateappendixa' => 'dashboard#generateappendixa'
end

ccm/app/models/cybercontrol.rb
class Cybercontrol < ActiveRecord::Base
  has_many :enclavecontrols
  
  # internal attribute for concatinated name/number
  def controlNameNumber
    cntrlName = self.controlFamilyCode + " #{self.controlNumber}" + ((self.enhancement != nil) ? "(#{self.enhancement})" : '')
    cntrlName
  end
  
  # internal attribute for current controlName
  def controlFamilyName
    cntrlFcName = ""
    if self.enhancement == nil then
      cntrlFcName = self.controlName
    else
      cfc = Cybercontrol.where("enhancement is null and controlFamilyCode = '#{self.controlFamilyCode}' and controlNumber = #{self.controlNumber}").first
      cntrlFcName = cfc.controlName
    end
    cntrlFcName
  end
  
  # internal attribute for the set of control family names
  def controlFamilySet
    conf = Configvalue.where(:name => :controlrevision).first
    controlRev = conf.ivalue
    cntrlFam = Cybercontrol.where("enhancement is null and controlNumber = 1 and Revision = #{controlRev}")
    cntrlFam
  end
  
  # internal attribute for the set of root controls
  def controlSet
    cntrl = Cybercontrol.where("enhancement is null")
    cntrl
  end
end

ccm/app/controllers/cybercontrols_controller.rb
class CybercontrolsController < ApplicationController
  # GET /cybercontrols
  # GET /cybercontrols.xml
  def index
    @cybercontrols = Cybercontrol.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cybercontrols }
    end
  end

  def indextest
    cc = Cybercontrol.first
    @cybercontrols = cc.controlFamilySet

    respond_to do |format|
      format.html # indextest.html.erb
      format.xml  { render :xml => @cybercontrols }
    end
  end

  # GET /cybercontrols/1
  # GET /cybercontrols/1.xml
  def show
    @cybercontrol = Cybercontrol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cybercontrol }
    end
  end

  # GET /cybercontrols/new
  # GET /cybercontrols/new.xml
  def new
    @cybercontrol = Cybercontrol.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cybercontrol }
    end
  end

  # GET /cybercontrols/1/edit
  def edit
    @cybercontrol = Cybercontrol.find(params[:id])
  end

  # POST /cybercontrols
  # POST /cybercontrols.xml
  def create
    @cybercontrol = Cybercontrol.new(params[:cybercontrol])

    respond_to do |format|
      if @cybercontrol.save
        format.html { redirect_to(@cybercontrol, :notice => 'Cybercontrol was successfully created.') }
        format.xml  { render :xml => @cybercontrol, :status => :created, :location => @cybercontrol }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cybercontrol.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cybercontrols/1
  # PUT /cybercontrols/1.xml
  def update
    @cybercontrol = Cybercontrol.find(params[:id])

    respond_to do |format|
      if @cybercontrol.update_attributes(params[:cybercontrol])
        format.html { redirect_to(@cybercontrol, :notice => 'Cybercontrol was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cybercontrol.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cybercontrols/1
  # DELETE /cybercontrols/1.xml
  def destroy
    @cybercontrol = Cybercontrol.find(params[:id])
    @cybercontrol.destroy

    respond_to do |format|
      format.html { redirect_to(cybercontrols_url) }
      format.xml  { head :ok }
    end
  end
end

ccm/app/helpers/cybercontrols_helper.rb
module CybercontrolsHelper
end

ccm/app/views/cybercontrols/_form.html.erb
<%= form_for(@cybercontrol) do |f| %>
  <% if @cybercontrol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cybercontrol.errors.count, "error") %> prohibited this cybercontrol from being saved:</h2>

      <ul>
      <% @cybercontrol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :originalID %><br />
    <%= f.text_field :originalID %>
  </div>
  <div class="field">
    <%= f.label :Revision %><br />
    <%= f.text_field :Revision %>
  </div>
  <div class="field">
    <%= f.label :controlNumber %><br />
    <%= f.text_field :controlNumber %>
  </div>
  <div class="field">
    <%= f.label :parentControlKey %><br />
    <%= f.text_field :parentControlKey %>
  </div>
  <div class="field">
    <%= f.label :controlFamilyCode %><br />
    <%= f.text_field :controlFamilyCode %>
  </div>
  <div class="field">
    <%= f.label :controlName %><br />
    <%= f.text_field :controlName %>
  </div>
  <div class="field">
    <%= f.label :controlType %><br />
    <%= f.text_field :controlType %>
  </div>
  <div class="field">
    <%= f.label :enhancement %><br />
    <%= f.text_field :enhancement %>
  </div>
  <div class="field">
    <%= f.label :controlDescription %><br />
    <%= f.text_area :controlDescription %>
  </div>
  <div class="field">
    <%= f.label :impactLevel %><br />
    <%= f.text_field :impactLevel %>
  </div>
  <div class="field">
    <%= f.label :criticalControl %><br />
    <%= f.check_box :criticalControl %>
  </div>
  <div class="field">
    <%= f.label :guidance %><br />
    <%= f.text_area :guidance %>
  </div>
  <div class="field">
    <%= f.label :quarterly %><br />
    <%= f.check_box :quarterly %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :withdrawn %><br />
    <%= f.check_box :withdrawn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/cybercontrols/edit.html.erb
<h1>Editing cybercontrol</h1>

<%= render 'form' %>

<%= link_to 'Show', @cybercontrol %> |
<%= link_to 'Back', cybercontrols_path %>

ccm/app/views/cybercontrols/index.html.erb
<h1>Listing cybercontrols</h1>

<table>
  <tr>
    <th>Control/<br>Revision</th>
    <th>Parent</th>
    <th>Name</th>
    <th>Type /<br>
    Enhancement</th>
    <th>Description</th>
    <th>Impactlevel</th>
    <th>Crit</th>
    <th></th>
  </tr>

<% @cybercontrols.each do |cybercontrol| %>
  <tr valign=top>
    <td><%= cybercontrol.controlNameNumber %><br>
    <%= cybercontrol.Revision %></td>
    <td><%= cybercontrol.parentControlKey %></td>
    <td><%= cybercontrol.controlName %></td>
    <td><%= cybercontrol.controlType %> /<br>
    <%= cybercontrol.enhancement %></td>
    <td><%= cybercontrol.controlDescription %></td>
    <td><%= cybercontrol.impactLevel %></td>
    <td><%= cybercontrol.criticalControl %></td>
    <td align=center><%= link_to 'Show', cybercontrol %><br>
    <%= link_to 'Edit', edit_cybercontrol_path(cybercontrol) %><br>
    <%= link_to 'Destroy', cybercontrol, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cybercontrol', new_cybercontrol_path %>

ccm/app/views/cybercontrols/indextest.html.erb
<h1>Listing cybercontrols</h1>

<table>
  <tr>
    <th>Control/<br>Revision</th>
    <th>Parent</th>
    <th>Name</th>
    <th>Type</th>
    <th>Enhancement</th>
    <th>Description</th>
    <th>Impactlevel</th>
    <th>Crit</th>
    <th></th>
  </tr>

<% @cybercontrols.each do |cybercontrol| %>
  <tr valign=top>
    <td><%= cybercontrol.cName %><br>
    <%= cybercontrol.Revision %></td>
    <td><%= cybercontrol.parentControlKey %></td>
    <td><%= cybercontrol.controlName %></td>
    <td><%= cybercontrol.controlType %></td>
    <td><%= cybercontrol.enhancement %></td>
    <td><%= cybercontrol.controlDescription %></td>
    <td><%= cybercontrol.impactLevel %></td>
    <td><%= cybercontrol.criticalControl %></td>
    <td align=center><%= link_to 'Show', cybercontrol %><br>
    <%= link_to 'Edit', edit_cybercontrol_path(cybercontrol) %><br>
    <%= link_to 'Destroy', cybercontrol, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cybercontrol', new_cybercontrol_path %>

ccm/app/views/cybercontrols/new.html.erb
<h1>New cybercontrol</h1>

<%= render 'form' %>

<%= link_to 'Back', cybercontrols_path %>

ccm/app/views/cybercontrols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Originalid:</b>
  <%= @cybercontrol.originalID %>
</p>

<p>
  <b>Revision:</b>
  <%= @cybercontrol.Revision %>
</p>

<p>
  <b>Controlnumber:</b>
  <%= @cybercontrol.controlNumber %>
</p>

<p>
  <b>Parentcontrolkey:</b>
  <%= @cybercontrol.parentControlKey %>
</p>

<p>
  <b>Controlfamilycode:</b>
  <%= @cybercontrol.controlFamilyCode %>
</p>

<p>
  <b>Controlname:</b>
  <%= @cybercontrol.controlName %>
</p>

<p>
  <b>Controltype:</b>
  <%= @cybercontrol.controlType %>
</p>

<p>
  <b>Enhancement:</b>
  <%= @cybercontrol.enhancement %>
</p>

<p>
  <b>Controldescription:</b>
  <%= @cybercontrol.controlDescription %>
</p>

<p>
  <b>Impactlevel:</b>
  <%= @cybercontrol.impactLevel %>
</p>

<p>
  <b>Criticalcontrol:</b>
  <%= @cybercontrol.criticalControl %>
</p>

<p>
  <b>Guidance:</b>
  <%= @cybercontrol.guidance %>
</p>

<p>
  <b>Quarterly:</b>
  <%= @cybercontrol.quarterly %>
</p>

<p>
  <b>Priority:</b>
  <%= @cybercontrol.priority %>
</p>

<p>
  <b>Withdrawn:</b>
  <%= @cybercontrol.withdrawn %>
</p>

<p>
  <b>Created At:</b>
  <%= @cybercontrol.created_at %>
</p>

<p>
  <b>Updated At:</b>
  <%= @cybercontrol.updated_at %>
</p>



<%= link_to 'Edit', edit_cybercontrol_path(@cybercontrol) %> |
<%= link_to 'Back', cybercontrols_path %>