ccm/config/routes.rb
Ccm::Application.routes.draw do

  devise_for :users

  resources :configvalues

  resources :enclavequarters

  resources :enclaves

  resources :enclavecontrols

  resources :cybercontrols

  resources :people

  get "home/index"

   root :to => "dashboard#show"

  match 'dashboard/show(/:fcode)(/:id)(/:encntrq)' => 'dashboard#show'
  match 'dashboard/tools' => 'dashboard#tools'
  match 'dashboard/populate(/:year)(/:quarter)' => 'dashboard#populate'
  match 'dashboard/processexcelfile(/:filepath)' => 'dashboard#processexcelfile'
  match 'dashboard/generateappendixa' => 'dashboard#generateappendixa'
end

ccm/app/models/enclavecontrol.rb
class Enclavecontrol < ActiveRecord::Base
  belongs_to :cybercontrol
  belongs_to :enclave
  belongs_to :enclavequarter

  # internal attribute for id of the implementation status
  def implementationStatusID
    temp = Implementationstatus.where("name = ?", self.SSPImplementationStatus)
    statusID = temp.first.id
    statusID
  end
  
  # internal attribute for id of the test method
  def testMethodID
    temp = Testmethod.where("name = ?", self.testMethod)
    methodID = temp.first.id
    methodID
  end
  
  # internal attribute for id of the test results
  def testResultID
    temp = Testresult.where("name = ?", self.testResult)
    resultID = temp.first.id
    resultID
  end
  
  # internal attribute for set of current enclavecontrols
  def currentSet
    eq = Enclavequarter.first
    year = eq.currentYear
    quarter = eq.currentQuarter
    temp = Enclavecontrol.where("enclaveYear = #{year} AND enclaveQuarter = #{quarter}")
    temp
  end
  
  # apply update to all enclaves with same quarter, year, and control
  def applyToAll(id)
    # debug info to log
    #Rails.logger.error "\n" + "enclavecontrol.applyToAll - Got Here 1 - id=#{id}\n"
    
    # get source record
    ec = Enclavecontrol.find(id)
    
    #
    ecSet = Enclavecontrol.where("cybercontrol_id=#{ec.cybercontrol_id} AND enclaveYear=#{ec.enclaveYear} AND enclaveQuarter=#{ec.enclaveQuarter} AND id<>#{id}")
    
    ecSet.each do |item|
      item.RMF = ec.RMF
      item.SSPImplementationStatus = ec.SSPImplementationStatus
      item.SSPImplementationDescription = ec.SSPImplementationDescription
      item.implementingDocumentationOrArticfacts = ec.implementingDocumentationOrArticfacts
      item.deviationIdentifier = ec.deviationIdentifier
      item.testMethod = ec.testMethod
      item.testProcedure = ec.testProcedure
      item.plannedTestDate = ec.plannedTestDate
      item.scheduledTestYear = ec.scheduledTestYear
      item.actualTestDate = ec.actualTestDate
      item.testResult = ec.testResult
      item.testResultDescription = ec.testResultDescription
      item.assessorName = ec.assessorName
      item.cAndADoc = ec.cAndADoc
      item.controlReference = ec.controlReference
      item.save
      
    end
    
    1
    
  end

end

ccm/app/controllers/enclavecontrols_controller.rb
class EnclavecontrolsController < ApplicationController
  # GET /enclavecontrols
  # GET /enclavecontrols.xml
  def index
    @enclavecontrols = Enclavecontrol.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @enclavecontrols }
    end
  end

  # GET /enclavecontrols/1
  # GET /enclavecontrols/1.xml
  def show
    @enclavecontrol = Enclavecontrol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @enclavecontrol }
    end
  end

  # GET /enclavecontrols/new
  # GET /enclavecontrols/new.xml
  def new
    @enclavecontrol = Enclavecontrol.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @enclavecontrol }
    end
  end

  # GET /enclavecontrols/1/edit
  def edit
    @enclavecontrol = Enclavecontrol.find(params[:id])
    temp = Implementationstatus.first
    @implementationstatus = temp.nameArray
    temp = Testmethod.first
    @testmethods = temp.nameArray
    temp = Testresult.first
    @testresults = temp.nameArray
  end

  # POST /enclavecontrols
  # POST /enclavecontrols.xml
  def create
    @enclavecontrol = Enclavecontrol.new(params[:enclavecontrol])

    respond_to do |format|
      if @enclavecontrol.save
        format.html { redirect_to(@enclavecontrol, :notice => 'Enclavecontrol was successfully created.') }
        format.xml  { render :xml => @enclavecontrol, :status => :created, :location => @enclavecontrol }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @enclavecontrol.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /enclavecontrols/1
  # PUT /enclavecontrols/1.xml
  def update
    @enclavecontrol = Enclavecontrol.find(params[:id])
    doApplyToAll = params[:applytoall]

    respond_to do |format|
      if @enclavecontrol.update_attributes(params[:enclavecontrol])
        # debug info to log
        #Rails.logger.error "\n" + "enclavecontrols_controller - Got Here 1 - doApplyToAll=#{doApplyToAll}\n"
        if doApplyToAll.to_i == 1 then
          ecTemp = Enclavecontrol.first
          ecTemp.applyToAll(@enclavecontrol.id)
        end
        format.html { redirect_to(@enclavecontrol, :notice => 'Enclavecontrol was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @enclavecontrol.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /enclavecontrols/1
  # DELETE /enclavecontrols/1.xml
  def destroy
    @enclavecontrol = Enclavecontrol.find(params[:id])
    @enclavecontrol.destroy

    respond_to do |format|
      format.html { redirect_to(enclavecontrols_url) }
      format.xml  { head :ok }
    end
  end
end

ccm/app/helpers/enclavecontrols_helper.rb
module EnclavecontrolsHelper
end

ccm/app/views/enclavecontrols/Copy of _form2.html.erb
<%= form_for(@enclavecontrol) do |f| %>
  <% if @enclavecontrol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enclavecontrol.errors.count, "error") %> prohibited this enclavecontrol from being saved:</h2>

      <ul>
      <% @enclavecontrol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enclave_id %><br />
    <!--%= f.text_field :enclave_id %--><%= @enclavecontrol.enclave.Name %>
  </div>
  <div class="field">
    <%= f.label :enclaveYear %><br />
    <!--%= f.text_field :enclaveYear %--><%= @enclavecontrol.enclaveYear %>
  </div>
  <div class="field">
    <%= f.label :cybercontrol_id %><br />
    <!--%= f.text_field :cybercontrol_id %--><%= @enclavecontrol.cybercontrol.controlNameNumber %>
  </div>
  <div class="field">
    <%= f.label :RMF %><br />
    <%= f.check_box :RMF %>
  </div>
  <div class="field">
    <%= f.label :SSPImplementationStatus %><br />
    <!--%= f.text_field :SSPImplementationStatus %-->
    <%= collection_select(f, :SSPImplementationStatus, @implementationstatus, :name, :name, {:include_blank => true, :selected => @enclavecontrol.SSPImplementationStatus}) %>
  </div>
  <div class="field">
    <%= f.label :SSPImplementationDescription %><br />
    <%= f.text_area :SSPImplementationDescription %>
  </div>
  <div class="field">
    <%= f.label :implementingDocumentationOrArticfacts %><br />
    <%= f.text_field :implementingDocumentationOrArticfacts %>
  </div>
  <div class="field">
    <%= f.label :deviationIdentifier %><br />
    <%= f.text_field :deviationIdentifier %>
  </div>
  <div class="field">
    <%= f.label :testMethod %><br />
    <!--%= f.text_field :testMethod %-->
    <%= collection_select(f, :testMethod, @testmethods, :name, :name, {:include_blank => true, :selected => @enclavecontrol.testMethod}) %>
  </div>
  <div class="field">
    <%= f.label :testProcedure %><br />
    <%= f.text_field :testProcedure %>
  </div>
  <div class="field">
    <%= f.label :plannedTestDate %><br />
    <%= f.date_select :plannedTestDate, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :scheduledTestYear %><br />
    <%= f.text_field :scheduledTestYear %>
  </div>
  <div class="field">
    <%= f.label :actualTestDate %><br />
    <%= f.date_select :actualTestDate, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :testResult %><br />
    <!--%= f.text_field :testResult %-->
    <%= collection_select(f, :testResult, @testresults, :name, :name, {:include_blank => true, :selected => @enclavecontrol.testResult}) %>
  </div>
  <div class="field">
    <%= f.label :testResultDescription %><br />
    <%= f.text_area :testResultDescription %>
  </div>
  <div class="field">
    <%= f.label :assessorName %><br />
    <%= f.text_field :assessorName %>
  </div>
  <div class="field">
    <%= f.label :cAndADoc %><br />
    <%= f.text_field :cAndADoc %>
  </div>
  <div class="field">
    <%= f.label :controlReference %><br />
    <%= f.text_field :controlReference %>
  </div>
  <div class="field">
    <%= f.label :enclavequarter_id %><br />
    <%= f.text_field :enclavequarter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/enclavecontrols/_form.html.erb
<%= form_for(@enclavecontrol) do |f| %>
  <% if @enclavecontrol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enclavecontrol.errors.count, "error") %> prohibited this enclavecontrol from being saved:</h2>

      <ul>
      <% @enclavecontrol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enclave_id %><br />
    <%= f.text_field :enclave_id %>
  </div>
  <div class="field">
    <%= f.label :enclaveYear %><br />
    <%= f.text_field :enclaveYear %>
  </div>
  <div class="field">
    <%= f.label :cybercontrol_id %><br />
    <%= f.text_field :cybercontrol_id %>
  </div>
  <div class="field">
    <%= f.label :RMF %><br />
    <%= f.check_box :RMF %>
  </div>
  <div class="field">
    <%= f.label :SSPImplementationStatus %><br />
    <%= f.text_field :SSPImplementationStatus %>
  </div>
  <div class="field">
    <%= f.label :SSPImplementationDescription %><br />
    <%= f.text_area :SSPImplementationDescription %>
  </div>
  <div class="field">
    <%= f.label :implementingDocumentationOrArticfacts %><br />
    <%= f.text_field :implementingDocumentationOrArticfacts %>
  </div>
  <div class="field">
    <%= f.label :deviationIdentifier %><br />
    <%= f.text_field :deviationIdentifier %>
  </div>
  <div class="field">
    <%= f.label :testMethod %><br />
    <%= f.text_field :testMethod %>
  </div>
  <div class="field">
    <%= f.label :testProcedure %><br />
    <%= f.text_field :testProcedure %>
  </div>
  <div class="field">
    <%= f.label :plannedTestDate %><br />
    <%= f.date_select :plannedTestDate, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :scheduledTestYear %><br />
    <%= f.text_field :scheduledTestYear %>
  </div>
  <div class="field">
    <%= f.label :actualTestDate %><br />
    <%= f.date_select :actualTestDate, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :testResult %><br />
    <%= f.text_field :testResult %>
  </div>
  <div class="field">
    <%= f.label :testResultDescription %><br />
    <%= f.text_area :testResultDescription %>
  </div>
  <div class="field">
    <%= f.label :assessorName %><br />
    <%= f.text_field :assessorName %>
  </div>
  <div class="field">
    <%= f.label :cAndADoc %><br />
    <%= f.text_field :cAndADoc %>
  </div>
  <div class="field">
    <%= f.label :controlReference %><br />
    <%= f.text_field :controlReference %>
  </div>
  <div class="field">
    <%= f.label :enclavequarter_id %><br />
    <%= f.text_field :enclavequarter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/enclavecontrols/_form2.html.erb
<%= form_for(@enclavecontrol) do |f| %>
  <% if @enclavecontrol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enclavecontrol.errors.count, "error") %> prohibited this enclavecontrol from being saved:</h2>

      <ul>
      <% @enclavecontrol.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><br />
    Enclave: <%= @enclavecontrol.enclave.Name %> &nbsp; &nbsp; Year/Quarter: <%= @enclavecontrol.enclavequarter.enclaveYear %>/<%= @enclavecontrol.enclavequarter.enclaveQuarter %> &nbsp; &nbsp; 
    Control: <%= @enclavecontrol.cybercontrol.controlNameNumber %><br />
    <div class="field">
      <br /><%= f.label :SSPImplementationDescription, "SSP Implementation Description" %><br />
      <%= f.text_area :SSPImplementationDescription, :size =>"100x6" %>
    </div>
    <div class="field">
      <br /><%= f.label :testResultDescription, "Test Result Description" %><br />
      <%= f.text_area :testResultDescription, :size =>"100x6" %>
    </div>
  
  </div>
  
  <div class="yui-gb">
    <div class="yui-u first">
      <div class="field">
        <br /><%= f.label :RMF, "RMF" %>
        <%= f.check_box :RMF %>
      </div>
      <div class="field">
        <%= f.label :SSPImplementationStatus, "SSP Implementation Status" %><br />
        <%= f.select :SSPImplementationStatus, @implementationstatus, {:include_blank => true}, :selected => @enclavecontrol.SSPImplementationStatus %>
      </div>
      <div class="field">
        <%= f.label :implementingDocumentationOrArticfacts, "Implementing Documentation Or Articfacts" %><br />
        <%= f.text_field :implementingDocumentationOrArticfacts %>
      </div>
      <div class="field">
        <%= f.label :deviationIdentifier, "Deviation Identifier" %><br />
        <%= f.text_field :deviationIdentifier %>
      </div>
      <div class="field">
        <%= f.label :testMethod, "Test Method" %><br />
        <%= f.select :testMethod, @testmethods, {:include_blank => true}, :selected => @enclavecontrol.testMethod %>
      </div>
    </div>
    <div class="yui-u">
      <div class="field">
        <br /><%= f.label :testProcedure, "Test Procedure" %><br />
        <%= f.text_field :testProcedure %>
      </div>
      <div class="field">
        <%= f.label :plannedTestDate, "Planned Test Date" %><br />
        <%= f.date_select :plannedTestDate, :include_blank => true %>
      </div>
      <div class="field">
        <%= f.label :scheduledTestYear, "Scheduled Test Year" %><br />
        <%= f.text_field :scheduledTestYear %>
      </div>
      <div class="field">
        <%= f.label :actualTestDate, "Actual Test Date" %><br />
        <%= f.date_select :actualTestDate, :include_blank => true %>
      </div>
    </div>
    <div class="yui-u">
      <div class="field">
        <br /><%= f.label :testResult, "Test Result" %><br />
        <%= f.select :testResult, @testresults, {:include_blank => true}, :selected => @enclavecontrol.testResult %>
      </div>
      <div class="field">
        <%= f.label :assessorName, "Assessor Name" %><br />
        <%= f.text_field :assessorName %>
      </div>
      <div class="field">
        <%= f.label :cAndADoc, "C And A Doc" %><br />
        <%= f.text_field :cAndADoc %>
      </div>
      <div class="field">
        <%= f.label :controlReference, "Control Reference" %><br />
        <%= f.text_field :controlReference %>
      </div>
      <!--div class="field"-->
        <!--%= f.label :enclavequarter_id %><br /-->
        <!--%= f.text_field :enclavequarter_id %-->
      <!--/div-->
      <div class="field">
        <br />Apply To All Enclaves
        <input type=hidden name=applytoall value="0">
        <input type=checkbox name=applytoall value="1">
      </div>
    </div>
  </div>
  <div class="actions" align=center>
    <br />
    <%= f.submit %>
  </div>
<% end %>

ccm/app/views/enclavecontrols/edit.html.erb
<h1>Editing Enclave Control</h1>

<%= render 'form2' %>

<%= link_to 'Show', @enclavecontrol %> |
<%= link_to 'Back', "/dashboard/show/#{@enclavecontrol.cybercontrol.controlFamilyCode}/#{@enclavecontrol.cybercontrol.id}/#{@enclavecontrol.id}" %>
<!--%= link_to 'Back', enclavecontrols_path %-->

ccm/app/views/enclavecontrols/index.html.erb
<h1>Listing enclavecontrols</h1>

<table>
  <tr valign=bottom>
    <th>Enclave /<br>
    Year /<br>
    Qtr</th>
    <th>Control /<br>
    RMF /<br>
    SSP Status</th>
    <th>SSP Description</th>
    <th>Deviation /<br>
    Test Method</th>
    <th>Test Procedure</th>
    <!--th>Planned<br>Test Date</th>
    <th>Scheduled<br>Test Year</th>
    <th>Actual<br>Test Date</th>
    <th>Test<br>Result</th>
    <th>Test<br>Result<br>Description</th>
    <th>Assessor Name</th>
    <th>C&A Doc</th>
    <th>Control Reference</th-->
    <th></th>
  </tr>

<% @enclavecontrols.each do |enclavecontrol| %>
  <tr valign=top>
    <td><%= enclavecontrol.enclave.Name %> /<br>
    <%= enclavecontrol.enclaveYear %> /<br>
    <%= enclavecontrol.enclavequarter.enclaveQuarter %></td>
    <td><%= enclavecontrol.cybercontrol.controlNameNumber %> /<br>
    <%= enclavecontrol.RMF %> /<br>
    <%= enclavecontrol.SSPImplementationStatus %></td>
    <% temp = ((enclavecontrol.SSPImplementationDescription != nil) ? enclavecontrol.SSPImplementationDescription : " ") %>
    <td><%= raw colapsestring("lefirst#{enclavecontrol.id}", temp.gsub(/\n/,"<br>\n"), 200, false, true) %></td>
    <td><%= ((enclavecontrol.deviationIdentifier == '1') ? "True" : "False") %> /<br>
    <%= enclavecontrol.testMethod %></td>
    <% temp = ((enclavecontrol.testProcedure != nil) ? enclavecontrol.testProcedure : " ") %>
    <td><%= raw colapsestring("lesecond#{enclavecontrol.id}", temp.gsub(/\n/,"<br>\n"), 200, false, true) %></td>
    <!--td><-%= enclavecontrol.plannedTestDate %></td>
    <td><-%= enclavecontrol.scheduledTestYear %></td>
    <td><-%= enclavecontrol.actualTestDate %></td>
    <td><-%= enclavecontrol.testResult %></td>
    <td><-%= enclavecontrol.testResultDescription %></td>
    <td><-%= enclavecontrol.assessorName %></td>
    <td><-%= enclavecontrol.cAndADoc %></td>
    <td><-%= enclavecontrol.controlReference %></td-->
    <td align=center><%= link_to 'Show', enclavecontrol %><br>
    <%= link_to 'Edit', edit_enclavecontrol_path(enclavecontrol) if current_user.operator? %><br>
    <%= link_to 'Destroy', enclavecontrol, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enclavecontrol', new_enclavecontrol_path %>

ccm/app/views/enclavecontrols/new.html.erb
<h1>New enclavecontrol</h1>

<%= render 'form' %>

<%= link_to 'Back', enclavecontrols_path %>

ccm/app/views/enclavecontrols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Enclave:</b>
  <%= @enclavecontrol.enclave_id %>
</p>

<p>
  <b>Enclaveyear:</b>
  <%= @enclavecontrol.enclaveYear %>
</p>

<p>
  <b>ControlID:</b>
  <%= @enclavecontrol.cybercontrol_id %>
</p>

<p>
  <b>RMF:</b>
  <%= @enclavecontrol.RMF %>
</p>

<p>
  <b>SSPImplementationStatus:</b>
  <%= @enclavecontrol.SSPImplementationStatus %>
</p>

<p>
  <b>SSPImplementationDescription:</b>
  <%= @enclavecontrol.SSPImplementationDescription %>
</p>

<p>
  <b>ImplementingDocumentationOrArticfacts:</b>
  <%= @enclavecontrol.implementingDocumentationOrArticfacts %>
</p>

<p>
  <b>DeviationIdentifier:</b>
  <%= @enclavecontrol.deviationIdentifier %>
</p>

<p>
  <b>TestMethod:</b>
  <%= @enclavecontrol.testMethod %>
</p>

<p>
  <b>TestProcedure:</b>
  <%= @enclavecontrol.testProcedure %>
</p>

<p>
  <b>PlannedTestDate:</b>
  <%= @enclavecontrol.plannedTestDate %>
</p>

<p>
  <b>ScheduledTestYear:</b>
  <%= @enclavecontrol.scheduledTestYear %>
</p>

<p>
  <b>ActualTestDate:</b>
  <%= @enclavecontrol.actualTestDate %>
</p>

<p>
  <b>TestResult:</b>
  <%= @enclavecontrol.testResult %>
</p>

<p>
  <b>TestResultDescription:</b>
  <%= @enclavecontrol.testResultDescription %>
</p>

<p>
  <b>AssessorName:</b>
  <%= @enclavecontrol.assessorName %>
</p>

<p>
  <b>C and A Doc:</b>
  <%= @enclavecontrol.cAndADoc %>
</p>

<p>
  <b>ControlReference:</b>
  <%= @enclavecontrol.controlReference %>
</p>

<p>
  <b>EnclaveQuarters:</b>
  <%= @enclavecontrol.enclavequarter_id %>
</p>

<p>
  <b>Created At:</b>
  <%= @enclavecontrol.created_at %>
</p>

<p>
  <b>Updated At:</b>
  <%= @enclavecontrol.updated_at %>
</p>


<%= link_to 'Edit', edit_enclavecontrol_path(@enclavecontrol) if current_user.operator? %> | 
<%= link_to 'Back', "/dashboard/show/#{@enclavecontrol.cybercontrol.controlFamilyCode}/#{@enclavecontrol.cybercontrol.id}/#{@enclavecontrol.id}" %>
<!--%= link_to 'Back', enclavecontrols_path %-->